export const DO_LOGIN = 'DO_LOGIN';
export const DO_LOGIN_RES = 'DO_LOGIN_RES';

export const DO_FORGOTPASSWORD = 'DO_FORGOTPASSWORD';
export const DO_FORGOTPASSWORD_RES = 'DO_FORGOTPASSWORD_RES';

export const DO_ALL_USERS = 'DO_ALL_USERS';
export const DO_ALL_USERS_RES = 'DO_ALL_USERS_RES';

export const DO_CREATE_USER = 'DO_CREATE_USER';
export const DO_CREATE_USER_RES = 'DO_CREATE_USER_RES';

export const DO_DELETE_USER = 'DO_DELETE_USER';
export const DO_DELETE_USER_RES = 'DO_DELETE_USER_RES';

export const DO_UPDATE_USER = 'DO_UPDATE_USER';
export const DO_UPDATE_USER_RES = 'DO_UPDATE_USER_RES';

export const DO_USER_APPROVED = 'DO_USER_APPROVED';
export const DO_USER_APPROVED_RES = 'DO_USER_APPROVED_RES';

export const FETCH_All_COUNTRY = 'FETCH_All_COUNTRY';
export const FETCH_All_COUNTRY_RES = 'FETCH_All_COUNTRY_RES';

export const FETCH_All_STATE = 'FETCH_All_STATE';
export const FETCH_All_STATE_RES = 'FETCH_All_STATE_RES';

export const FETCH_All_CITY = 'FETCH_All_CITY';
export const FETCH_All_CITY_RES = 'FETCH_All_CITY_RES';

export const FETCH_All_APPLICATION = 'FETCH_All_APPLICATION';
export const FETCH_All_APPLICATION_RES = 'FETCH_All_APPLICATION_RES';

export const CREATE_APPLICATION = 'CREATE_APPLICATION';
export const CREATE_APPLICATION_RES = 'CREATE_APPLICATION_RES';

export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const UPDATE_APPLICATION_RES = 'UPDATE_APPLICATION_RES';

export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const DELETE_APPLICATION_RES = 'DELETE_APPLICATION_RES';

export const UPLOAD_APPLICATION_ICON = 'UPLOAD_APPLICATION_ICON';
export const UPLOAD_APPLICATION_ICON_RES = 'UPLOAD_APPLICATION_ICON_RES';

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CREATE_NOTIFICATION_RES = 'CREATE_NOTIFICATION_RES';

export const DO_ALL_SEARCH_USERS = 'DO_ALL_SEARCH_USERS';
export const DO_ALL_SEARCH_USERS_RES = 'DO_ALL_SEARCH_USERS_RES';

export const DO_USER_APPROVE_APP = 'DO_USER_APPROVE_APP';
export const DO_USER_APPROVE_APP_RES = 'DO_USER_APPROVE_APP_RES';

export const DO_RESETPASSWORD = 'DO_RESETPASSWORD';
export const DO_RESETPASSWORD_RES = 'DO_RESETPASSWORD_RES';

export const DO_CREATE_ADMIN = 'DO_CREATE_ADMIN';
export const DO_CREATE_ADMIN_RES = 'DO_CREATE_ADMIN_RES';

export const DO_APP_ADMIN = 'DO_APP_ADMIN';
export const DO_APP_ADMIN_RES = 'DO_APP_ADMIN_RES';

export const DELETE_ADMIN = 'DELETE_ADMIN';
export const DELETE_ADMIN_RES = 'DELETE_ADMIN_RES';

export const DO_CHECK_USER = 'DO_CHECK_USER';
export const DO_CHECK_USER_RES = 'DO_CHECK_USER_RES';

export const FETCH_NOVUSBI = 'FETCH_NOVUSBI';
export const FETCH_NOVUSBI_RES = 'FETCH_NOVUSBI_RES';

export const DO_NOVUSBI_CREATE = 'DO_NOVUSBI_CREATE';
export const DO_NOVUSBI_CREATE_RES = 'DO_NOVUSBI_CREATE_RES';

export const DO_NOVUSBI_ARTICLE = 'DO_NOVUSBI_ARTICLE';
export const DO_NOVUSBI_ARTICLE_RES = 'DO_NOVUSBI_ARTICLE_RES';

export const DO_NOVUSBI_ARTICLE_UPDATE = 'DO_NOVUSBI_ARTICLE_UPDATE';
export const DO_NOVUSBI_ARTICLE_UPDATE_RES = 'DO_NOVUSBI_ARTICLE_UPDATE_RES';

export const FETCH_CONTENTLIST = 'FETCH_CONTENTLIST';
export const FETCH_CONTENTLIST_RES = 'FETCH_CONTENTLIST_RES';

export const FETCH_CATEGORYLIST = 'FETCH_CATEGORYLIST';
export const FETCH_CATEGORYLIST_RES = 'FETCH_CATEGORYLIST_RES';

export const FETCH_ALLCATEGORYLIST = 'FETCH_ALLCATEGORYLIST';
export const FETCH_ALLCATEGORYLIST_RES = 'FETCH_ALLCATEGORYLIST_RES';

export const FETCH_COMMENTLIST = 'FETCH_COMMENTLIST';
export const FETCH_COMMENTLIST_RES = 'FETCH_COMMENTLIST_RES';

export const FETCH_TRASHLIST = 'FETCH_TRASHLIST';
export const FETCH_TRASHLIST_RES = 'FETCH_TRASHLIST_RES';

export const FETCH_SUBCATEGORYLIST = 'FETCH_SUBCATEGORYLIST';
export const FETCH_SUBCATEGORYLIST_RES = 'FETCH_SUBCATEGORYLIST_RES';

export const FETCH_ARTICLELIST = 'FETCH_ARTICLELIST';
export const FETCH_ARTICLELIST_RES = 'FETCH_ARTICLELIST_RES';

export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const UPDATE_CONTENT_RES = 'UPDATE_CONTENT_RES';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_RES = 'UPDATE_CATEGORY_RES';

export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY';
export const UPDATE_SUBCATEGORY_RES = 'UPDATE_SUBCATEGORY_RES';

export const DELETE_CATEGORYLIST = 'DELETE_CATEGORYLIST';
export const DELETE_CATEGORYLIST_RES = 'DELETE_CATEGORYLIST_RES';

export const DELETE_SUBCATEGORYLIST = 'DELETE_SUBCATEGORYLIST';
export const DELETE_SUBCATEGORYLIST_RES = 'DELETE_SUBCATEGORYLIST_RES';

export const DELETE_CONTENTLIST = 'DELETE_CONTENTLIST';
export const DELETE_CONTENTLIST_RES = 'DELETE_CONTENTLIST_RES';

export const STATUS_CONTENTLIST = 'STATUS_CONTENTLIST';
export const STATUS_CONTENTLIST_RES = 'STATUS_CONTENTLIST_RES';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_RES = 'CREATE_CATEGORY_RES';

export const BANNER_LIST = 'BANNER_LIST';
export const BANNER_LIST_RES = 'BANNER_LIST_RES';

export const DELETE_BANNERLIST = 'DELETE_BANNERLIST';
export const DELETE_BANNERLIST_RES = 'DELETE_BANNERLIST_RES';

export const CREATE_BANNER = 'CREATE_BANNER';
export const CREATE_BANNER_RES = 'CREATE_BANNER_RES';

export const UPDATE_BANNER = 'UPDATE_BANNER';
export const UPDATE_BANNER_RES = 'UPDATE_BANNER_RES';

export const REGION_LIST = 'REGION_LIST';
export const REGION_LIST_RES = 'REGION_LIST_RES';

export const DELETE_REGIONLIST = 'DELETE_REGIONLIST';
export const DELETE_REGIONLIST_RES = 'DELETE_REGIONLIST_RES';

export const CREATE_REGION = 'CREATE_REGION';
export const CREATE_REGION_RES = 'CREATE_REGION_RES';

export const UPDATE_REGION = 'UPDATE_REGION';
export const UPDATE_REGION_RES = 'UPDATE_REGION_RES';


